// Code generated by internal/cmd/genfacade; DO NOT EDIT.
// Source: github.com/weftgo/weft/core/wefttest

package wefttest

//go:generate go run github.com/weftgo/weft/internal/cmd/genfacade -src ../core/wefttest -import github.com/weftgo/weft/core/wefttest -as corewefttest -pkg wefttest -out facade.go -rewrite github.com/weftgo/weft/core=github.com/weftgo/weft

import (
	"testing"

	"github.com/weftgo/weft"
	corewefttest "github.com/weftgo/weft/core/wefttest"
)

// ConformInfo reports nil when middleware m forwards the inner model's
// identity unchanged — the convention ModelMiddleware documents
// ("implementations should forward Info") — and an error naming the
// offender otherwise. Use it in a middleware's own test suite to turn
// the documented convention into a checked fact.
func ConformInfo(m weft.ModelMiddleware) error { return corewefttest.ConformInfo(m) }

// ConformInfoT is ConformInfo as a test helper: it fails t instead of
// returning an error.
func ConformInfoT(t testing.TB, m weft.ModelMiddleware) { corewefttest.ConformInfoT(t, m) }

// Flatten returns evs with every Nested event replaced by its inner
// event, recursively — the child's events as the child emitted them —
// for asserting a nested run's behaviour without unwrapping by hand.
//
//	evs := collect(parentStream)
//	want := []core.Event{core.RunStart{}, core.StepStart{}, ...}
//	slices.Equal(want, Flatten(evs))
func Flatten(evs []weft.Event) []weft.Event { return corewefttest.Flatten(evs) }

// Golden compares got against the committed golden file at path. With
// -update it writes got (creating parent directories) and logs which
// files it created or changed, so a regeneration run says what was
// stale rather than rewriting everything silently; an up-to-date file
// is left untouched. Otherwise a mismatch fails the test with a line
// diff, and a missing file fails with a hint to regenerate. Note the
// flag goes after the package list
// (`go test ./... -update`): placed before it, the go tool routes it to
// the wrong package's binary.
//
//	func TestManifest(t *testing.T) {
//		b, err := core.Manifest(newAgent())
//		if err != nil { t.Fatal(err) }
//		wefttest.Golden(t, "weft.json", b)
//	}
func Golden(t testing.TB, path string, got []byte) { corewefttest.Golden(t, path, got) }

// ErrScriptExhausted is the stream error a Model yields when the agent
// makes more model calls than the script provides — almost always a test
// bug worth failing loudly.
var ErrScriptExhausted = corewefttest.ErrScriptExhausted

// Turn is the script for one model call, built by Say, ToolCalls, or Fail.
type Turn = corewefttest.Turn

// Say scripts a completed assistant reply: one text delta, then a normal
// stop. Usage is fixed at 10 input / 5 output tokens per scripted step, so
// usage accounting is assertable.
func Say(text string) Turn { return corewefttest.Say(text) }

// Think prefixes then with a scripted reasoning delta: Think("plan",
// ToolCalls(...)) is a step that reasons and then requests tools. The
// reasoning carries no signature; signed blocks are scripted with raw
// model events.
func Think(text string, then Turn) Turn { return corewefttest.Think(text, then) }

// Call describes one scripted tool invocation.
type Call = corewefttest.Call

// ToolCalls scripts a step that requests tool calls. Call IDs are assigned
// "call_1", "call_2", ... within the turn unless set explicitly.
func ToolCalls(calls ...Call) Turn { return corewefttest.ToolCalls(calls...) }

// MaxTokens scripts a step that hit the output-token limit: the text so
// far, then a max_tokens finish. The run records it on
// RunResult.StopReason (and the StepRecord) rather than failing;
// truncated tool-call arguments decode as error results the model
// recovers from.
func MaxTokens(text string) Turn { return corewefttest.MaxTokens(text) }

// Fail scripts a model failure: the stream errors immediately with err.
func Fail(err error) Turn { return corewefttest.Fail(err) }

// Args marshals v as the JSON arguments of a scripted Call:
//
//	wefttest.Call{Name: "lookup", Args: wefttest.Args(lookupIn{Order: 42})}
//
// A value that cannot be marshalled is a test-construction bug and
// panics at the call site naming the type.
func Args(v any) string { return corewefttest.Args(v) }

// Raw scripts a step that plays exactly the events given, appending
// nothing — the way to script a signed reasoning block, a
// ModelToolCallDelta progress sequence, or a stream that violates the
// Model contract (no ModelFinish, two of them, an event after the
// finish) so a test can pin how the loop reports ErrModelContract.
// Raw still honours ctx like every scripted turn: it is malformed by
// content, never by ignoring cancellation.
func Raw(events ...weft.ModelEvent) Turn { return corewefttest.Raw(events...) }

// SayThenFail scripts a mid-stream failure: one text delta, then the
// stream errors with err. The loop discards the partial turn and
// reports err; mw.Retry sees a failure after output.
func SayThenFail(text string, err error) Turn { return corewefttest.SayThenFail(text, err) }

// Model is a scripted core.Model. It plays one Turn per Stream call, in
// order, and records every ModelRequest it received for assertions.
type Model = corewefttest.Model

// Script returns a Model that plays the turns in order.
func Script(turns ...Turn) *Model { return corewefttest.Script(turns...) }

// Request is one recorded ModelRequest with matchers for the assertions
// agent tests make most; every field of the request stays reachable
// through the embedded value.
type Request = corewefttest.Request

// ErrNoFixture is the stream error Replay yields for a request no
// fixture answers — a new or changed request since the recording, or a
// fresh checkout without fixtures. Re-record with Record.
var ErrNoFixture = corewefttest.ErrNoFixture

// Record returns a Model that plays inner and records every request
// and the stream inner produced for it under dir/<t.Name()>/, one JSON
// file per request in conversation order, for Replay to answer later.
// It is the deliberate, local, key-holding half of record/replay:
// call it from a test only when re-recording, never in CI. The test's
// directory is replaced, not merged.
//
// The recording switch belongs to the suite that holds the provider
// key, not to wefttest — Golden's -update rewrites a comparison, while
// Record spends money. The recommended shape (WEFT_RECORD is the
// suggested name, so suites converge on one spelling):
//
//	func model(t *testing.T) core.Model {
//	    if os.Getenv("WEFT_RECORD") != "" { // the suite's own switch; wefttest never reads it
//	        return wefttest.Record(t, "testdata/replay", openai.New(os.Getenv("OPENAI_API_KEY"), "gpt-5"))
//	    }
//	    return wefttest.Replay(t, "testdata/replay")
//	}
//
// Record never checks WEFT_MODEL_REQUESTS: inner does, so a recording
// made under deny stores the denial's error text and the diff shows it.
func Record(t testing.TB, dir string, inner weft.Model) weft.Model {
	return corewefttest.Record(t, dir, inner)
}

// Replay returns a Model that answers each request from the fixture
// Record wrote for it under dir/<t.Name()>/, matched by the request's
// key (messages, tool names, thinking level and the sequential flag —
// not the system prompt). It makes no request, holds no key, and
// ignores WEFT_MODEL_REQUESTS like every wefttest model. A request
// with no fixture fails the stream with ErrNoFixture naming what was
// wanted; repeated identical requests replay in recorded order.
//
// The fixtures are pretty-printed JSON a reviewer reads in a diff —
// the request's messages (a changed prompt shows as a changed fixture)
// and the model's events — so re-recording is the review, exactly as
// ADR 0013 says for wire fixtures.
func Replay(t testing.TB, dir string) weft.Model { return corewefttest.Replay(t, dir) }

// Steers is a deterministic steering source: the messages registered for
// a step are delivered at that step's drain points, and nothing drains
// anywhere else. Keyed by step — not by time or channel state — so a
// replayed run (Replay) cannot diverge from its recording: the
// delivered messages are part of the next model request's transcript,
// and a steer that differs from the recorded one misses its fixture
// loudly (ErrNoFixture) instead of drifting (ADR 0017, ADR 0019 §6).
// For the same reason a live test steers through this type too: the
// schedule the test ran is the schedule the file shows.
//
//	src := wefttest.NewSteers().At(0, core.User("prefer the left door"))
//	res, err := agt.Generate(ctx, core.Prompt("which door?"), src.Option())
type Steers = corewefttest.Steers

// NewSteers returns an empty Steers source; register deliveries with At.
func NewSteers() *Steers { return corewefttest.NewSteers() }
