// Code generated by internal/cmd/genfacade; DO NOT EDIT.
// Source: github.com/weftgo/weft/core/mw

package mw

//go:generate go run github.com/weftgo/weft/internal/cmd/genfacade -src ../core/mw -import github.com/weftgo/weft/core/mw -as coremw -pkg mw -out facade.go -rewrite github.com/weftgo/weft/core=github.com/weftgo/weft

import (
	"log/slog"
	"time"

	"github.com/weftgo/weft"
	coremw "github.com/weftgo/weft/core/mw"
)

// Fallback tries the given models, in order, when the wrapped model's
// stream fails before yielding any event — a provider outage, a
// capability gap (core.ErrUnsupported). A failure
// after events were yielded is not retried anywhere: the loop already
// consumed part of the reply, so it surfaces as the run error. Context
// cancellation and the WEFT_MODEL_REQUESTS kill switch never fall
// through. A max_tokens finish is a successful stream, not a failure —
// Fallback does not switch on it. Info reports the primary model.
func Fallback(models ...weft.Model) weft.ModelMiddleware { return coremw.Fallback(models...) }

// FallbackWhen is Fallback with a predicate: the next model is tried
// only for errors that satisfy when. A nil predicate uses Fallback's
// default (anything but cancellation and the kill switch).
func FallbackWhen(when func(error) bool, models ...weft.Model) weft.ModelMiddleware {
	return coremw.FallbackWhen(when, models...)
}

// Log records one line per model call at Debug level — the request
// summary before the call and the finish (or error) after it — on the
// given logger, or slog.Default when nil. Lines carry the model, the
// message and tool counts, and on finish the stop reason, usage, tool
// call count, and duration. Placed outermost it sees the outcome of
// retries and fallbacks; placed innermost, each attempt.
func Log(l *slog.Logger) weft.ModelMiddleware { return coremw.Log(l) }

// RepairJSON re-encodes a tool call's arguments once when they are not
// valid JSON — the common damage is a reply cut mid-object or wrapped
// in a Markdown fence. Unterminated strings, objects, and arrays are
// closed and fences stripped; when the result parses, it replaces the
// original. Arguments that cannot be repaired pass through unchanged
// and fail decoding as they would have, so the model still sees an
// INVALID_INPUT result. Only tool-call events are touched.
func RepairJSON() weft.ModelMiddleware { return coremw.RepairJSON() }

// ErrRetryAfterTooLong is wrapped around a provider error whose
// retry-after ask exceeds MaxWait: rather than sleeping silently for
// minutes, Retry fails fast so an outer layer (a queue, a person) can
// decide. errors.Is on it, or on the provider's own error underneath.
var ErrRetryAfterTooLong = coremw.ErrRetryAfterTooLong

// RetryOption configures Retry.
type RetryOption = coremw.RetryOption

// MaxRetries sets how many times a failed call is retried (default 3).
// Zero disables retrying while keeping the retry-after and classifier
// behaviour observable through Log. Negative values are ignored — the
// core options' rule, stated here too.
func MaxRetries(n int) RetryOption { return coremw.MaxRetries(n) }

// BaseDelay sets the first backoff delay (default 500ms). Delays double
// per attempt — 0.5s, 1s, 2s, … — capped at 8s, each with ±25% jitter,
// unless the provider names its own retry-after, which wins. Zero is
// meaningful (no delay between attempts); negative values are ignored.
func BaseDelay(d time.Duration) RetryOption { return coremw.BaseDelay(d) }

// MaxWait bounds a provider's retry-after ask (default 60s): a longer
// ask fails fast wrapping ErrRetryAfterTooLong instead of sleeping.
// MaxWait(0) removes the cap — whatever the provider asks, Retry
// waits — and negative values are ignored.
func MaxWait(d time.Duration) RetryOption { return coremw.MaxWait(d) }

// Classifier replaces the default retryability test. The default
// retries core.ErrStreamIdle, net.Error values, and HTTP 408, 409, 429
// and 5xx responses reported by the vendor SDKs' error types; it never
// retries context cancellation, the kill switch, core.ErrUnsupported,
// quota and billing 4xx, or a context-window overflow — the last must
// route to compaction, not to the same request again.
func Classifier(fn func(error) bool) RetryOption { return coremw.Classifier(fn) }

// Retry retries a model call that fails before yielding any event —
// the request-level failures a provider reports up front: rate limits,
// overload, transport errors, an idle stream. The vendor SDKs already
// retry at the transport layer (their MaxRetries adapter options);
// Retry is the loop-visible logic layer above them, with backoff the
// caller can see in Log and a retry-after the provider sends honoured
// (retry-after-ms, retry-after, and x-should-retry headers). A failure
// after events were yielded is never retried: part of the reply has
// already reached the loop. Exhausted retries return the last error
// wrapped, so errors.As on the SDK's type still works. Pair Retry
// with the adapter's MaxRetries(0): the SDK's retries sleep on the
// provider's retry-after inside the adapter's idle timer (the wait for
// response headers is one gap), so a long ask fails ErrStreamIdle with
// the 429 discarded — here the same ask is honoured, capped by MaxWait,
// and visible in Log.
func Retry(opts ...RetryOption) weft.ModelMiddleware { return coremw.Retry(opts...) }

// Retryable is Retry's default classifier: true for core.ErrStreamIdle,
// net.Error values, and HTTP 408, 409, 429 and 5xx statuses found on
// the error (see HTTPStatus); false for context errors, the kill
// switch, core.ErrUnsupported, every other 4xx, a context-window
// overflow — the mapped sentinel (core.ErrContextOverflow, what the
// first-party adapters wrap) or the marker text itself (adapterkit's
// table, shared here) — which must route to compaction, not to the
// same request again. An x-should-retry header, when the provider
// sends one, overrides the status rule.
func Retryable(err error) bool { return coremw.Retryable(err) }

// RetryAfter extracts the provider's retry-after ask from the error's
// HTTP response headers: retry-after-ms (milliseconds), then
// retry-after (seconds, or an HTTP date relative to now). ok is false
// when the error carries no such header, or carries one whose value
// cannot become a duration — unparseable, negative, or too large to
// convert (ParseFloat accepts 1e19 and Infinity; the int64 conversion
// of those wraps negative, which would slip past the maxWait cap and
// sleep zero, turning a misbehaving gateway's ask into up to
// MaxRetries+1 back-to-back requests).
func RetryAfter(err error, now time.Time) (time.Duration, bool) { return coremw.RetryAfter(err, now) }

// HTTPStatus finds an HTTP status code on the error chain: the vendor
// SDKs' error types carry it as an exported StatusCode (openai-go,
// anthropic-sdk-go) or Code (google genai) integer field. The lookup is
// structural — mw imports no vendor SDK — and reports ok=false when no
// error on the chain has such a field.
func HTTPStatus(err error) (int, bool) { return coremw.HTTPStatus(err) }

// IsContextOverflow reports whether the error chain's text names a
// context-window overflow. Retry treats such an error as terminal;
// an adapter maps it to core.ErrContextOverflow. The vendor SDKs carry the provider's
// message on the error's own Error() — typed enough for the mapping,
// string-matched because mw imports no vendor SDK (ADR 0013's
// structural-lookup rule).
func IsContextOverflow(err error) bool { return coremw.IsContextOverflow(err) }

// Allow gates every tool call on a predicate over its core.Call. A
// denied call never runs: the model sees the error result `DENIED:
// tool "x" is not allowed` and the loop moves on — there is no retry,
// no prompt, no exception. Approval is a different seam
// (core.RequireApproval): Allow is the fixed policy, approval the
// deferred decision. Outside the loop (Agent.CallTool with a bare
// ctx) the Call is built from the call part alone. A nil permit allows
// every call — the middleware is a pass-through, so a policy that is
// configured off composes without a branch at the call site.
func Allow(permit func(weft.Call) bool) weft.ToolMiddleware { return coremw.Allow(permit) }

// Audit logs one line per tool call at Info level on the given logger
// (slog.Default when nil): run, step, call id, tool, duration, and the
// outcome — the model-visible error text, plus the internal cause when
// the error is a *core.ToolError with one. It changes nothing.
func Audit(l *slog.Logger) weft.ToolMiddleware { return coremw.Audit(l) }

// MapErrors shapes handler errors centrally before the loop renders
// them for the model. Errors that are already *core.ToolError pass
// through untouched, as do context errors and ErrApprovalRequired (the
// loop reads those). Every other error goes through fn; a nil fn
// installs the default, which hides the text — database messages,
// stack fragments, wrapped internals — behind `INTERNAL: tool "x"
// failed` while keeping the original as the ToolError's cause for
// Audit and errors.As.
func MapErrors(fn func(error) error) weft.ToolMiddleware { return coremw.MapErrors(fn) }
